#include <gtest/gtest.h>

#include <headers/variantx.hpp>
#include <string>

TEST(VariantxImpl, TraitsStaticAssertions) { namespace vi = variantx::impl; }

TEST(VariantxImpl, VariadicUnionStaticAssertions)
{
    namespace vi = variantx::impl;

    using V1 = vi::VariadicUnion<vi::Trait::Available, 0, int, float, double>;
    using V2 = vi::VariadicUnion<vi::Trait::TriviallyAvailable, 0, int, float, double>;
    using V3 = vi::VariadicUnion<vi::Trait::Unavailable, 0, int, float, double>;

    static_assert(std::is_destructible_v<V1> && !std::is_trivially_destructible_v<V1>);
    static_assert(std::is_destructible_v<V2> && std::is_trivially_destructible_v<V2>);
    static_assert(!std::is_destructible_v<V3> && !std::is_trivially_destructible_v<V3>);
}

// Generated By Gemini 2.5 Pro
namespace
{
    namespace vi = variantx::impl;

    class ImplBaseVisitationTest : public ::testing::Test

    {
    protected:
        using V1 = vi::Base<vi::Trait::Available, int, float, std::string>;

        using V2 = vi::Base<vi::Trait::Available, bool, double>;

        using V3 = vi::Base<vi::Trait::Available, bool, double, char>;  // Same size as V1

        V1 v1_int{std::in_place_index<0>, 42};

        V1 v1_float{std::in_place_index<1>, 3.14f};

        V1 v1_string{std::in_place_index<2>, "hello"};

        V2 v2_bool{std::in_place_index<0>, true};

        V2 v2_double{std::in_place_index<1>, 2.71};

        struct SingleVariantVisitor

        {
            std::string operator()(int i) const { return std::to_string(i); }

            std::string operator()(float f) const { return std::to_string(f); }

            std::string operator()(const std::string& s) const { return s; }
        };

        struct MultiVariantVisitor

        {
            double operator()(int i, bool b) const { return i + (b ? 1.0 : 0.0); }

            double operator()(int i, double d) const { return i + d; }

            double operator()(float f, bool b) const { return f + (b ? 1.0 : 0.0); }

            double operator()(float f, double d) const { return f + d; }

            double operator()(const std::string& s, bool b) const

            {
                return static_cast<double>(s.length()) + (b ? 1.0 : 0.0);
            }

            double operator()(const std::string& s, double d) const

            {
                return static_cast<double>(s.length()) + d;
            }
        };

        struct ReturnTypeVisitor

        {
            int operator()(int i) const { return i; }

            int operator()(float f) const { return static_cast<int>(f); }

            int operator()(const std::string& s) const { return static_cast<int>(s.length()); }
        };

        struct VoidVisitor

        {
            mutable int result = 0;

            void operator()(int i) const { result = i; }

            void operator()(float f) const { result = static_cast<int>(f); }

            void operator()(const std::string&) const { result = -1; }
        };

        struct VisitorAt

        {
            std::string operator()(int, bool) const { return "int, bool"; }

            std::string operator()(float, double) const { return "float, double"; }

            std::string operator()(const std::string&, char) const { return "string, char"; }
        };
    };

    TEST_F(ImplBaseVisitationTest, VisitAlternativeSingleVariant)

    {
        SingleVariantVisitor visitor;

        EXPECT_EQ(vi::visitation::Base::VisitAlternative(visitor, v1_int), "42");

        EXPECT_FLOAT_EQ(std::stof(vi::visitation::Base::VisitAlternative(visitor, v1_float)),
                        3.14f);

        EXPECT_EQ(vi::visitation::Base::VisitAlternative(visitor, v1_string), "hello");
    }

    TEST_F(ImplBaseVisitationTest, VisitAlternativeSingleVariantConst)

    {
        const V1 const_v1_int{std::in_place_index<0>, 42};

        SingleVariantVisitor visitor;

        EXPECT_EQ(vi::visitation::Base::VisitAlternative(visitor, const_v1_int), "42");
    }

    TEST_F(ImplBaseVisitationTest, VisitAlternativeMultipleVariants)

    {
        MultiVariantVisitor visitor;

        // v1_int (42), v2_bool (true)

        EXPECT_DOUBLE_EQ(vi::visitation::Base::VisitAlternative(visitor, v1_int, v2_bool), 43.0);

        // v1_int (42), v2_double (2.71)

        EXPECT_DOUBLE_EQ(vi::visitation::Base::VisitAlternative(visitor, v1_int, v2_double),

                         42.0 + 2.71);

        // v1_float (3.14f), v2_bool (true)

        EXPECT_NEAR(vi::visitation::Base::VisitAlternative(visitor, v1_float, v2_bool),

                    static_cast<double>(3.14f) + 1.0, 1e-6);

        // v1_float (3.14f), v2_double (2.71)

        EXPECT_NEAR(vi::visitation::Base::VisitAlternative(visitor, v1_float, v2_double),

                    static_cast<double>(3.14f) + 2.71, 1e-6);

        // v1_string ("hello"), v2_bool (true)

        EXPECT_DOUBLE_EQ(vi::visitation::Base::VisitAlternative(visitor, v1_string, v2_bool),

                         5.0 + 1.0);

        // v1_string ("hello"), v2_double (2.71)

        EXPECT_DOUBLE_EQ(vi::visitation::Base::VisitAlternative(visitor, v1_string, v2_double),

                         5.0 + 2.71);
    }

    TEST_F(ImplBaseVisitationTest, VisitAlternativeReturnType)

    {
        ReturnTypeVisitor visitor;

        EXPECT_EQ(vi::visitation::Base::VisitAlternative(visitor, v1_int), 42);

        EXPECT_EQ(vi::visitation::Base::VisitAlternative(visitor, v1_float), 3);

        EXPECT_EQ(vi::visitation::Base::VisitAlternative(visitor, v1_string), 5);
    }

    TEST_F(ImplBaseVisitationTest, VisitAlternativeVoidReturn)

    {
        VoidVisitor visitor;

        vi::visitation::Base::VisitAlternative(visitor, v1_int);

        EXPECT_EQ(visitor.result, 42);

        vi::visitation::Base::VisitAlternative(visitor, v1_float);

        EXPECT_EQ(visitor.result, 3);

        vi::visitation::Base::VisitAlternative(visitor, v1_string);

        EXPECT_EQ(visitor.result, -1);
    }

    TEST_F(ImplBaseVisitationTest, VisitAlternativeAt)

    {
        VisitorAt visitor;

        // index 0

        V1 v1_0{std::in_place_index<0>, 123};

        V3 v3_0{std::in_place_index<0>, true};

        auto result0 = vi::visitation::Base::VisitAlternativeAt(0, visitor, v1_0, v3_0);

        EXPECT_EQ(result0, "int, bool");

        // index 1

        V1 v1_1{std::in_place_index<1>, 1.23f};

        V3 v3_1{std::in_place_index<1>, 4.56};

        auto result1 = vi::visitation::Base::VisitAlternativeAt(1, visitor, v1_1, v3_1);

        EXPECT_EQ(result1, "float, double");

        // index 2

        V1 v1_2{std::in_place_index<2>, "test"};

        V3 v3_2{std::in_place_index<2>, 'x'};

        auto result2 = vi::visitation::Base::VisitAlternativeAt(2, visitor, v1_2, v3_2);

        EXPECT_EQ(result2, "string, char");
    }

}  // namespace
